service: cycler-api
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  memorySize: 256
  timeout: 30
  environment:
    DB_URL: ${ssm:cycler-db-url-${opt:stage}}
    NODE_ENV: production
custom:
  contentEncoding:
    contentCompression: 100
  scripts:
    hooks:
      'before:deploy:deploy': |
        npm run compile
functions:
  server:
    handler: lib/lambda.handler
    events:
      # Run Lambda by schedule to prevent long cold starts
      - schedule: rate(5 minutes)
      # Proxy all routes to Lambda
      - http:
          method: ANY
          path: '{proxy+}'
          cors: false
      - http:
          method: ANY
          path: /
          cors: false
plugins:
  - serverless-plugin-scripts # To run predeploy scripts
